//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMApp.UI.UnitOfWork {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientDto", Namespace="http://schemas.datacontract.org/2004/07/UserDbServices.DTO")]
    [System.SerializableAttribute()]
    public partial class ClientDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((this.ClientIdField.Equals(value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((this.DateTimeField.Equals(value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDto", Namespace="http://schemas.datacontract.org/2004/07/UserDbServices.DTO")]
    [System.SerializableAttribute()]
    public partial class OrderDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((this.ClientIdField.Equals(value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((this.DateTimeField.Equals(value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDto", Namespace="http://schemas.datacontract.org/2004/07/UserDbServices.DTO")]
    [System.SerializableAttribute()]
    public partial class UserDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LoginAndPasswordIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LoginAndPasswordId {
            get {
                return this.LoginAndPasswordIdField;
            }
            set {
                if ((this.LoginAndPasswordIdField.Equals(value) != true)) {
                    this.LoginAndPasswordIdField = value;
                    this.RaisePropertyChanged("LoginAndPasswordId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SurName {
            get {
                return this.SurNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurNameField, value) != true)) {
                    this.SurNameField = value;
                    this.RaisePropertyChanged("SurName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginAndPasswordDto", Namespace="http://schemas.datacontract.org/2004/07/UserDbServices.DTO")]
    [System.SerializableAttribute()]
    public partial class LoginAndPasswordDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LoginAndPasswordIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LoginAndPasswordId {
            get {
                return this.LoginAndPasswordIdField;
            }
            set {
                if ((this.LoginAndPasswordIdField.Equals(value) != true)) {
                    this.LoginAndPasswordIdField = value;
                    this.RaisePropertyChanged("LoginAndPasswordId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UnitOfWork.IUnityOfWork")]
    public interface IUnityOfWork {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdersRepository/GetAllOrders", ReplyAction="http://tempuri.org/IOrdersRepository/GetAllOrdersResponse")]
        UserAuthorizationModule.UnitOfWork.Order[] GetAllOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdersRepository/GetAllOrders", ReplyAction="http://tempuri.org/IOrdersRepository/GetAllOrdersResponse")]
        System.Threading.Tasks.Task<UserAuthorizationModule.UnitOfWork.Order[]> GetAllOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdersRepository/GetOrder", ReplyAction="http://tempuri.org/IOrdersRepository/GetOrderResponse")]
        UserAuthorizationModule.UnitOfWork.Order GetOrder(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdersRepository/GetOrder", ReplyAction="http://tempuri.org/IOrdersRepository/GetOrderResponse")]
        System.Threading.Tasks.Task<UserAuthorizationModule.UnitOfWork.Order> GetOrderAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdersRepository/CreateOrder", ReplyAction="http://tempuri.org/IOrdersRepository/CreateOrderResponse")]
        void CreateOrder(UserAuthorizationModule.UnitOfWork.Order item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdersRepository/CreateOrder", ReplyAction="http://tempuri.org/IOrdersRepository/CreateOrderResponse")]
        System.Threading.Tasks.Task CreateOrderAsync(UserAuthorizationModule.UnitOfWork.Order item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdersRepository/UpdateOrder", ReplyAction="http://tempuri.org/IOrdersRepository/UpdateOrderResponse")]
        void UpdateOrder(UserAuthorizationModule.UnitOfWork.Order item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdersRepository/UpdateOrder", ReplyAction="http://tempuri.org/IOrdersRepository/UpdateOrderResponse")]
        System.Threading.Tasks.Task UpdateOrderAsync(UserAuthorizationModule.UnitOfWork.Order item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdersRepository/DeleteOrder", ReplyAction="http://tempuri.org/IOrdersRepository/DeleteOrderResponse")]
        void DeleteOrder(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdersRepository/DeleteOrder", ReplyAction="http://tempuri.org/IOrdersRepository/DeleteOrderResponse")]
        System.Threading.Tasks.Task DeleteOrderAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsRepository/GetAllClients", ReplyAction="http://tempuri.org/IClientsRepository/GetAllClientsResponse")]
        UserAuthorizationModule.UnitOfWork.Client[] GetAllClients();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsRepository/GetAllClients", ReplyAction="http://tempuri.org/IClientsRepository/GetAllClientsResponse")]
        System.Threading.Tasks.Task<UserAuthorizationModule.UnitOfWork.Client[]> GetAllClientsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsRepository/GetClient", ReplyAction="http://tempuri.org/IClientsRepository/GetClientResponse")]
        UserAuthorizationModule.UnitOfWork.Client GetClient(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsRepository/GetClient", ReplyAction="http://tempuri.org/IClientsRepository/GetClientResponse")]
        System.Threading.Tasks.Task<UserAuthorizationModule.UnitOfWork.Client> GetClientAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsRepository/CreateClient", ReplyAction="http://tempuri.org/IClientsRepository/CreateClientResponse")]
        void CreateClient(UserAuthorizationModule.UnitOfWork.Client item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsRepository/CreateClient", ReplyAction="http://tempuri.org/IClientsRepository/CreateClientResponse")]
        System.Threading.Tasks.Task CreateClientAsync(UserAuthorizationModule.UnitOfWork.Client item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsRepository/UpdateClient", ReplyAction="http://tempuri.org/IClientsRepository/UpdateClientResponse")]
        void UpdateClient(UserAuthorizationModule.UnitOfWork.Client item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsRepository/UpdateClient", ReplyAction="http://tempuri.org/IClientsRepository/UpdateClientResponse")]
        System.Threading.Tasks.Task UpdateClientAsync(UserAuthorizationModule.UnitOfWork.Client item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsRepository/DeleteClient", ReplyAction="http://tempuri.org/IClientsRepository/DeleteClientResponse")]
        void DeleteClient(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsRepository/DeleteClient", ReplyAction="http://tempuri.org/IClientsRepository/DeleteClientResponse")]
        System.Threading.Tasks.Task DeleteClientAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginAndPasswordsRepository/GetAllLoginAndPassword", ReplyAction="http://tempuri.org/ILoginAndPasswordsRepository/GetAllLoginAndPasswordResponse")]
        UserAuthorizationModule.UnitOfWork.LoginAndPassword[] GetAllLoginAndPassword();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginAndPasswordsRepository/GetAllLoginAndPassword", ReplyAction="http://tempuri.org/ILoginAndPasswordsRepository/GetAllLoginAndPasswordResponse")]
        System.Threading.Tasks.Task<UserAuthorizationModule.UnitOfWork.LoginAndPassword[]> GetAllLoginAndPasswordAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginAndPasswordsRepository/GetLoginAndPassword", ReplyAction="http://tempuri.org/ILoginAndPasswordsRepository/GetLoginAndPasswordResponse")]
        UserAuthorizationModule.UnitOfWork.LoginAndPassword GetLoginAndPassword(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginAndPasswordsRepository/GetLoginAndPassword", ReplyAction="http://tempuri.org/ILoginAndPasswordsRepository/GetLoginAndPasswordResponse")]
        System.Threading.Tasks.Task<UserAuthorizationModule.UnitOfWork.LoginAndPassword> GetLoginAndPasswordAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginAndPasswordsRepository/CreateLoginAndPassword", ReplyAction="http://tempuri.org/ILoginAndPasswordsRepository/CreateLoginAndPasswordResponse")]
        void CreateLoginAndPassword(UserAuthorizationModule.UnitOfWork.LoginAndPassword item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginAndPasswordsRepository/CreateLoginAndPassword", ReplyAction="http://tempuri.org/ILoginAndPasswordsRepository/CreateLoginAndPasswordResponse")]
        System.Threading.Tasks.Task CreateLoginAndPasswordAsync(UserAuthorizationModule.UnitOfWork.LoginAndPassword item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginAndPasswordsRepository/UpdateLoginAndPassword", ReplyAction="http://tempuri.org/ILoginAndPasswordsRepository/UpdateLoginAndPasswordResponse")]
        void UpdateLoginAndPassword(UserAuthorizationModule.UnitOfWork.LoginAndPassword item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginAndPasswordsRepository/UpdateLoginAndPassword", ReplyAction="http://tempuri.org/ILoginAndPasswordsRepository/UpdateLoginAndPasswordResponse")]
        System.Threading.Tasks.Task UpdateLoginAndPasswordAsync(UserAuthorizationModule.UnitOfWork.LoginAndPassword item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginAndPasswordsRepository/DeleteLoginAndPassword", ReplyAction="http://tempuri.org/ILoginAndPasswordsRepository/DeleteLoginAndPasswordResponse")]
        void DeleteLoginAndPassword(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginAndPasswordsRepository/DeleteLoginAndPassword", ReplyAction="http://tempuri.org/ILoginAndPasswordsRepository/DeleteLoginAndPasswordResponse")]
        System.Threading.Tasks.Task DeleteLoginAndPasswordAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersRepository/GetAllUsers", ReplyAction="http://tempuri.org/IUsersRepository/GetAllUsersResponse")]
        UserAuthorizationModule.UnitOfWork.User[] GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersRepository/GetAllUsers", ReplyAction="http://tempuri.org/IUsersRepository/GetAllUsersResponse")]
        System.Threading.Tasks.Task<UserAuthorizationModule.UnitOfWork.User[]> GetAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersRepository/GetUser", ReplyAction="http://tempuri.org/IUsersRepository/GetUserResponse")]
        UserAuthorizationModule.UnitOfWork.User GetUser(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersRepository/GetUser", ReplyAction="http://tempuri.org/IUsersRepository/GetUserResponse")]
        System.Threading.Tasks.Task<UserAuthorizationModule.UnitOfWork.User> GetUserAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersRepository/CreateUser", ReplyAction="http://tempuri.org/IUsersRepository/CreateUserResponse")]
        void CreateUser(UserAuthorizationModule.UnitOfWork.User item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersRepository/CreateUser", ReplyAction="http://tempuri.org/IUsersRepository/CreateUserResponse")]
        System.Threading.Tasks.Task CreateUserAsync(UserAuthorizationModule.UnitOfWork.User item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersRepository/UpdateUser", ReplyAction="http://tempuri.org/IUsersRepository/UpdateUserResponse")]
        void UpdateUser(UserAuthorizationModule.UnitOfWork.User item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersRepository/UpdateUser", ReplyAction="http://tempuri.org/IUsersRepository/UpdateUserResponse")]
        System.Threading.Tasks.Task UpdateUserAsync(UserAuthorizationModule.UnitOfWork.User item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersRepository/DeleteUser", ReplyAction="http://tempuri.org/IUsersRepository/DeleteUserResponse")]
        void DeleteUser(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersRepository/DeleteUser", ReplyAction="http://tempuri.org/IUsersRepository/DeleteUserResponse")]
        System.Threading.Tasks.Task DeleteUserAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnityOfWork/Save", ReplyAction="http://tempuri.org/IUnityOfWork/SaveResponse")]
        void Save();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnityOfWork/Save", ReplyAction="http://tempuri.org/IUnityOfWork/SaveResponse")]
        System.Threading.Tasks.Task SaveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnityOfWork/GetAllClientDtos", ReplyAction="http://tempuri.org/IUnityOfWork/GetAllClientDtosResponse")]
        CRMApp.UI.UnitOfWork.ClientDto[] GetAllClientDtos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnityOfWork/GetAllClientDtos", ReplyAction="http://tempuri.org/IUnityOfWork/GetAllClientDtosResponse")]
        System.Threading.Tasks.Task<CRMApp.UI.UnitOfWork.ClientDto[]> GetAllClientDtosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnityOfWork/GetAllOrderDtos", ReplyAction="http://tempuri.org/IUnityOfWork/GetAllOrderDtosResponse")]
        CRMApp.UI.UnitOfWork.OrderDto[] GetAllOrderDtos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnityOfWork/GetAllOrderDtos", ReplyAction="http://tempuri.org/IUnityOfWork/GetAllOrderDtosResponse")]
        System.Threading.Tasks.Task<CRMApp.UI.UnitOfWork.OrderDto[]> GetAllOrderDtosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnityOfWork/GetAllUserDtos", ReplyAction="http://tempuri.org/IUnityOfWork/GetAllUserDtosResponse")]
        CRMApp.UI.UnitOfWork.UserDto[] GetAllUserDtos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnityOfWork/GetAllUserDtos", ReplyAction="http://tempuri.org/IUnityOfWork/GetAllUserDtosResponse")]
        System.Threading.Tasks.Task<CRMApp.UI.UnitOfWork.UserDto[]> GetAllUserDtosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnityOfWork/GetAllOrdersCurrentUser", ReplyAction="http://tempuri.org/IUnityOfWork/GetAllOrdersCurrentUserResponse")]
        CRMApp.UI.UnitOfWork.OrderDto[] GetAllOrdersCurrentUser(int currentUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnityOfWork/GetAllOrdersCurrentUser", ReplyAction="http://tempuri.org/IUnityOfWork/GetAllOrdersCurrentUserResponse")]
        System.Threading.Tasks.Task<CRMApp.UI.UnitOfWork.OrderDto[]> GetAllOrdersCurrentUserAsync(int currentUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnityOfWork/GetAllOrdersCurrentClient", ReplyAction="http://tempuri.org/IUnityOfWork/GetAllOrdersCurrentClientResponse")]
        CRMApp.UI.UnitOfWork.OrderDto[] GetAllOrdersCurrentClient(int currentClientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnityOfWork/GetAllOrdersCurrentClient", ReplyAction="http://tempuri.org/IUnityOfWork/GetAllOrdersCurrentClientResponse")]
        System.Threading.Tasks.Task<CRMApp.UI.UnitOfWork.OrderDto[]> GetAllOrdersCurrentClientAsync(int currentClientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnityOfWork/GetAllOrderDtosTheCompany", ReplyAction="http://tempuri.org/IUnityOfWork/GetAllOrderDtosTheCompanyResponse")]
        CRMApp.UI.UnitOfWork.OrderDto[] GetAllOrderDtosTheCompany(string companyName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnityOfWork/GetAllOrderDtosTheCompany", ReplyAction="http://tempuri.org/IUnityOfWork/GetAllOrderDtosTheCompanyResponse")]
        System.Threading.Tasks.Task<CRMApp.UI.UnitOfWork.OrderDto[]> GetAllOrderDtosTheCompanyAsync(string companyName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnityOfWork/UserDtoAuthorization", ReplyAction="http://tempuri.org/IUnityOfWork/UserDtoAuthorizationResponse")]
        CRMApp.UI.UnitOfWork.UserDto UserDtoAuthorization(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnityOfWork/UserDtoAuthorization", ReplyAction="http://tempuri.org/IUnityOfWork/UserDtoAuthorizationResponse")]
        System.Threading.Tasks.Task<CRMApp.UI.UnitOfWork.UserDto> UserDtoAuthorizationAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnityOfWork/GetAllClientsCurrentUser", ReplyAction="http://tempuri.org/IUnityOfWork/GetAllClientsCurrentUserResponse")]
        CRMApp.UI.UnitOfWork.ClientDto[] GetAllClientsCurrentUser(int currentUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnityOfWork/GetAllClientsCurrentUser", ReplyAction="http://tempuri.org/IUnityOfWork/GetAllClientsCurrentUserResponse")]
        System.Threading.Tasks.Task<CRMApp.UI.UnitOfWork.ClientDto[]> GetAllClientsCurrentUserAsync(int currentUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnityOfWork/AppUsers", ReplyAction="http://tempuri.org/IUnityOfWork/AppUsersResponse")]
        void AppUsers(CRMApp.UI.UnitOfWork.UserDto updateUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnityOfWork/AppUsers", ReplyAction="http://tempuri.org/IUnityOfWork/AppUsersResponse")]
        System.Threading.Tasks.Task AppUsersAsync(CRMApp.UI.UnitOfWork.UserDto updateUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnityOfWork/AddLoginAndPasswords", ReplyAction="http://tempuri.org/IUnityOfWork/AddLoginAndPasswordsResponse")]
        void AddLoginAndPasswords(CRMApp.UI.UnitOfWork.LoginAndPasswordDto updateLoginAndPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnityOfWork/AddLoginAndPasswords", ReplyAction="http://tempuri.org/IUnityOfWork/AddLoginAndPasswordsResponse")]
        System.Threading.Tasks.Task AddLoginAndPasswordsAsync(CRMApp.UI.UnitOfWork.LoginAndPasswordDto updateLoginAndPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnityOfWork/AddClients", ReplyAction="http://tempuri.org/IUnityOfWork/AddClientsResponse")]
        void AddClients(CRMApp.UI.UnitOfWork.ClientDto updateClient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnityOfWork/AddClients", ReplyAction="http://tempuri.org/IUnityOfWork/AddClientsResponse")]
        System.Threading.Tasks.Task AddClientsAsync(CRMApp.UI.UnitOfWork.ClientDto updateClient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnityOfWork/AddOrders", ReplyAction="http://tempuri.org/IUnityOfWork/AddOrdersResponse")]
        void AddOrders(CRMApp.UI.UnitOfWork.OrderDto updateOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnityOfWork/AddOrders", ReplyAction="http://tempuri.org/IUnityOfWork/AddOrdersResponse")]
        System.Threading.Tasks.Task AddOrdersAsync(CRMApp.UI.UnitOfWork.OrderDto updateOrder);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUnityOfWorkChannel : CRMApp.UI.UnitOfWork.IUnityOfWork, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UnityOfWorkClient : System.ServiceModel.ClientBase<CRMApp.UI.UnitOfWork.IUnityOfWork>, CRMApp.UI.UnitOfWork.IUnityOfWork {
        
        public UnityOfWorkClient() {
        }
        
        public UnityOfWorkClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UnityOfWorkClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UnityOfWorkClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UnityOfWorkClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UserAuthorizationModule.UnitOfWork.Order[] GetAllOrders() {
            return base.Channel.GetAllOrders();
        }
        
        public System.Threading.Tasks.Task<UserAuthorizationModule.UnitOfWork.Order[]> GetAllOrdersAsync() {
            return base.Channel.GetAllOrdersAsync();
        }
        
        public UserAuthorizationModule.UnitOfWork.Order GetOrder(int id) {
            return base.Channel.GetOrder(id);
        }
        
        public System.Threading.Tasks.Task<UserAuthorizationModule.UnitOfWork.Order> GetOrderAsync(int id) {
            return base.Channel.GetOrderAsync(id);
        }
        
        public void CreateOrder(UserAuthorizationModule.UnitOfWork.Order item) {
            base.Channel.CreateOrder(item);
        }
        
        public System.Threading.Tasks.Task CreateOrderAsync(UserAuthorizationModule.UnitOfWork.Order item) {
            return base.Channel.CreateOrderAsync(item);
        }
        
        public void UpdateOrder(UserAuthorizationModule.UnitOfWork.Order item) {
            base.Channel.UpdateOrder(item);
        }
        
        public System.Threading.Tasks.Task UpdateOrderAsync(UserAuthorizationModule.UnitOfWork.Order item) {
            return base.Channel.UpdateOrderAsync(item);
        }
        
        public void DeleteOrder(int id) {
            base.Channel.DeleteOrder(id);
        }
        
        public System.Threading.Tasks.Task DeleteOrderAsync(int id) {
            return base.Channel.DeleteOrderAsync(id);
        }
        
        public UserAuthorizationModule.UnitOfWork.Client[] GetAllClients() {
            return base.Channel.GetAllClients();
        }
        
        public System.Threading.Tasks.Task<UserAuthorizationModule.UnitOfWork.Client[]> GetAllClientsAsync() {
            return base.Channel.GetAllClientsAsync();
        }
        
        public UserAuthorizationModule.UnitOfWork.Client GetClient(int id) {
            return base.Channel.GetClient(id);
        }
        
        public System.Threading.Tasks.Task<UserAuthorizationModule.UnitOfWork.Client> GetClientAsync(int id) {
            return base.Channel.GetClientAsync(id);
        }
        
        public void CreateClient(UserAuthorizationModule.UnitOfWork.Client item) {
            base.Channel.CreateClient(item);
        }
        
        public System.Threading.Tasks.Task CreateClientAsync(UserAuthorizationModule.UnitOfWork.Client item) {
            return base.Channel.CreateClientAsync(item);
        }
        
        public void UpdateClient(UserAuthorizationModule.UnitOfWork.Client item) {
            base.Channel.UpdateClient(item);
        }
        
        public System.Threading.Tasks.Task UpdateClientAsync(UserAuthorizationModule.UnitOfWork.Client item) {
            return base.Channel.UpdateClientAsync(item);
        }
        
        public void DeleteClient(int id) {
            base.Channel.DeleteClient(id);
        }
        
        public System.Threading.Tasks.Task DeleteClientAsync(int id) {
            return base.Channel.DeleteClientAsync(id);
        }
        
        public UserAuthorizationModule.UnitOfWork.LoginAndPassword[] GetAllLoginAndPassword() {
            return base.Channel.GetAllLoginAndPassword();
        }
        
        public System.Threading.Tasks.Task<UserAuthorizationModule.UnitOfWork.LoginAndPassword[]> GetAllLoginAndPasswordAsync() {
            return base.Channel.GetAllLoginAndPasswordAsync();
        }
        
        public UserAuthorizationModule.UnitOfWork.LoginAndPassword GetLoginAndPassword(int id) {
            return base.Channel.GetLoginAndPassword(id);
        }
        
        public System.Threading.Tasks.Task<UserAuthorizationModule.UnitOfWork.LoginAndPassword> GetLoginAndPasswordAsync(int id) {
            return base.Channel.GetLoginAndPasswordAsync(id);
        }
        
        public void CreateLoginAndPassword(UserAuthorizationModule.UnitOfWork.LoginAndPassword item) {
            base.Channel.CreateLoginAndPassword(item);
        }
        
        public System.Threading.Tasks.Task CreateLoginAndPasswordAsync(UserAuthorizationModule.UnitOfWork.LoginAndPassword item) {
            return base.Channel.CreateLoginAndPasswordAsync(item);
        }
        
        public void UpdateLoginAndPassword(UserAuthorizationModule.UnitOfWork.LoginAndPassword item) {
            base.Channel.UpdateLoginAndPassword(item);
        }
        
        public System.Threading.Tasks.Task UpdateLoginAndPasswordAsync(UserAuthorizationModule.UnitOfWork.LoginAndPassword item) {
            return base.Channel.UpdateLoginAndPasswordAsync(item);
        }
        
        public void DeleteLoginAndPassword(int id) {
            base.Channel.DeleteLoginAndPassword(id);
        }
        
        public System.Threading.Tasks.Task DeleteLoginAndPasswordAsync(int id) {
            return base.Channel.DeleteLoginAndPasswordAsync(id);
        }
        
        public UserAuthorizationModule.UnitOfWork.User[] GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<UserAuthorizationModule.UnitOfWork.User[]> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
        
        public UserAuthorizationModule.UnitOfWork.User GetUser(int id) {
            return base.Channel.GetUser(id);
        }
        
        public System.Threading.Tasks.Task<UserAuthorizationModule.UnitOfWork.User> GetUserAsync(int id) {
            return base.Channel.GetUserAsync(id);
        }
        
        public void CreateUser(UserAuthorizationModule.UnitOfWork.User item) {
            base.Channel.CreateUser(item);
        }
        
        public System.Threading.Tasks.Task CreateUserAsync(UserAuthorizationModule.UnitOfWork.User item) {
            return base.Channel.CreateUserAsync(item);
        }
        
        public void UpdateUser(UserAuthorizationModule.UnitOfWork.User item) {
            base.Channel.UpdateUser(item);
        }
        
        public System.Threading.Tasks.Task UpdateUserAsync(UserAuthorizationModule.UnitOfWork.User item) {
            return base.Channel.UpdateUserAsync(item);
        }
        
        public void DeleteUser(int id) {
            base.Channel.DeleteUser(id);
        }
        
        public System.Threading.Tasks.Task DeleteUserAsync(int id) {
            return base.Channel.DeleteUserAsync(id);
        }
        
        public void Save() {
            base.Channel.Save();
        }
        
        public System.Threading.Tasks.Task SaveAsync() {
            return base.Channel.SaveAsync();
        }
        
        public CRMApp.UI.UnitOfWork.ClientDto[] GetAllClientDtos() {
            return base.Channel.GetAllClientDtos();
        }
        
        public System.Threading.Tasks.Task<CRMApp.UI.UnitOfWork.ClientDto[]> GetAllClientDtosAsync() {
            return base.Channel.GetAllClientDtosAsync();
        }
        
        public CRMApp.UI.UnitOfWork.OrderDto[] GetAllOrderDtos() {
            return base.Channel.GetAllOrderDtos();
        }
        
        public System.Threading.Tasks.Task<CRMApp.UI.UnitOfWork.OrderDto[]> GetAllOrderDtosAsync() {
            return base.Channel.GetAllOrderDtosAsync();
        }
        
        public CRMApp.UI.UnitOfWork.UserDto[] GetAllUserDtos() {
            return base.Channel.GetAllUserDtos();
        }
        
        public System.Threading.Tasks.Task<CRMApp.UI.UnitOfWork.UserDto[]> GetAllUserDtosAsync() {
            return base.Channel.GetAllUserDtosAsync();
        }
        
        public CRMApp.UI.UnitOfWork.OrderDto[] GetAllOrdersCurrentUser(int currentUserId) {
            return base.Channel.GetAllOrdersCurrentUser(currentUserId);
        }
        
        public System.Threading.Tasks.Task<CRMApp.UI.UnitOfWork.OrderDto[]> GetAllOrdersCurrentUserAsync(int currentUserId) {
            return base.Channel.GetAllOrdersCurrentUserAsync(currentUserId);
        }
        
        public CRMApp.UI.UnitOfWork.OrderDto[] GetAllOrdersCurrentClient(int currentClientId) {
            return base.Channel.GetAllOrdersCurrentClient(currentClientId);
        }
        
        public System.Threading.Tasks.Task<CRMApp.UI.UnitOfWork.OrderDto[]> GetAllOrdersCurrentClientAsync(int currentClientId) {
            return base.Channel.GetAllOrdersCurrentClientAsync(currentClientId);
        }
        
        public CRMApp.UI.UnitOfWork.OrderDto[] GetAllOrderDtosTheCompany(string companyName) {
            return base.Channel.GetAllOrderDtosTheCompany(companyName);
        }
        
        public System.Threading.Tasks.Task<CRMApp.UI.UnitOfWork.OrderDto[]> GetAllOrderDtosTheCompanyAsync(string companyName) {
            return base.Channel.GetAllOrderDtosTheCompanyAsync(companyName);
        }
        
        public CRMApp.UI.UnitOfWork.UserDto UserDtoAuthorization(string login, string password) {
            return base.Channel.UserDtoAuthorization(login, password);
        }
        
        public System.Threading.Tasks.Task<CRMApp.UI.UnitOfWork.UserDto> UserDtoAuthorizationAsync(string login, string password) {
            return base.Channel.UserDtoAuthorizationAsync(login, password);
        }
        
        public CRMApp.UI.UnitOfWork.ClientDto[] GetAllClientsCurrentUser(int currentUserId) {
            return base.Channel.GetAllClientsCurrentUser(currentUserId);
        }
        
        public System.Threading.Tasks.Task<CRMApp.UI.UnitOfWork.ClientDto[]> GetAllClientsCurrentUserAsync(int currentUserId) {
            return base.Channel.GetAllClientsCurrentUserAsync(currentUserId);
        }
        
        public void AppUsers(CRMApp.UI.UnitOfWork.UserDto updateUser) {
            base.Channel.AppUsers(updateUser);
        }
        
        public System.Threading.Tasks.Task AppUsersAsync(CRMApp.UI.UnitOfWork.UserDto updateUser) {
            return base.Channel.AppUsersAsync(updateUser);
        }
        
        public void AddLoginAndPasswords(CRMApp.UI.UnitOfWork.LoginAndPasswordDto updateLoginAndPassword) {
            base.Channel.AddLoginAndPasswords(updateLoginAndPassword);
        }
        
        public System.Threading.Tasks.Task AddLoginAndPasswordsAsync(CRMApp.UI.UnitOfWork.LoginAndPasswordDto updateLoginAndPassword) {
            return base.Channel.AddLoginAndPasswordsAsync(updateLoginAndPassword);
        }
        
        public void AddClients(CRMApp.UI.UnitOfWork.ClientDto updateClient) {
            base.Channel.AddClients(updateClient);
        }
        
        public System.Threading.Tasks.Task AddClientsAsync(CRMApp.UI.UnitOfWork.ClientDto updateClient) {
            return base.Channel.AddClientsAsync(updateClient);
        }
        
        public void AddOrders(CRMApp.UI.UnitOfWork.OrderDto updateOrder) {
            base.Channel.AddOrders(updateOrder);
        }
        
        public System.Threading.Tasks.Task AddOrdersAsync(CRMApp.UI.UnitOfWork.OrderDto updateOrder) {
            return base.Channel.AddOrdersAsync(updateOrder);
        }
    }
}
